### ISSUE TITLE
HA configuration sample

### ISSUE THREAD

**Issue by RuneNyhuus** [SmilyOrg/screenmqtt#2]
Is there a Home Assistant Configuration sample here??
I have some of it working.. but it cannot get the State of the screen. HA shows it as Off

And what about PC with multiple screens? it only turn one of the screens off :)

**Comment by MrHacky** [comment]
This is what i use to configure screenmqtt as a light in HA, maybe this will help.

```
light:
  - platform: mqtt
    name: "Desk"
    state_topic: "pchome/monitor/all/power/state"
    command_topic: "pchome/monitor/all/power/command"
    payload_on: "ON"
    payload_off: "OFF"
    optimistic: false
```

**Comment by SmilyOrg** [comment]
Hey, I don't have this set up right now, but this is how I had it configured:

```
switch:
   - platform: mqtt
     name: "Hexacompy Monitors"
     command_topic: "hexacompy/monitor/all/power/command"
     state_topic: "hexacompy/monitor/all/power/state"
```

It's possible that some HA updates since changed the behavior, so @MrHacky's config is probably a little more up to date (thanks for that!) 😊
